Repository rancher-sandbox/sbombastic, pull requests merged in 2024-12, with the labels that each got.

#51 fix(storage): add resourceVersion to list
  internal/storage/store.go
Labels: bug, storage

#53 chore(Tiltfile): add a development registry to Tilt
  Tiltfile
  examples/registry.yaml
  hack/registry.yaml
Labels: dx

#54 fix(worker): trivy db repositories
  internal/handlers/generate_sbom.go
  internal/handlers/scan_sbom.go
Labels: bug, worker

#55 ci: enable dependabot
  .github/dependabot.yml
Labels: chore, ci

#72 chore: fix kubernetes dependabot group
  .github/dependabot.yml
Labels: chore, ci
