Repository rancher-sandbox/sbombastic, pull requests merged in 2025-07, with the labels that each got.

#310 feat: support rancher global registry setting
  charts/sbombastic/templates/_helpers.tpl
  charts/sbombastic/templates/controller/deployment.yaml
  charts/sbombastic/templates/storage/deployment.yaml
  charts/sbombastic/templates/worker/deployment.yaml
  charts/sbombastic/tests/controller/deployment_test.yaml
  charts/sbombastic/tests/storage/deployment_test.yaml
  charts/sbombastic/tests/worker/deployment_test.yaml
  charts/sbombastic/values.yaml
Labels: helm

#331 fix: code generation
  Makefile
  api/storage/install/install.go
  api/v1alpha1/groupversion_info.go
  api/v1alpha1/registry_types.go
  api/v1alpha1/scanjob_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  charts/sbombastic/templates/crd/sbombastic.rancher.io_scanjobs.yaml
  hack/boilerplate.go.txt
  internal/controller/registry_controller.go
  internal/controller/registry_controller_test.go
  internal/controller/scanjob_controller.go
  internal/controller/scanjob_controller_test.go
  internal/controller/suite_test.go
  internal/controller/vulnerabilityreport_controller.go
Labels: chore, dx

#335 feat: add ScanJob webhook
  charts/sbombastic/templates/controller/cert-manager.yaml
  charts/sbombastic/templates/controller/deployment.yaml
  charts/sbombastic/templates/controller/service.yaml
  charts/sbombastic/templates/controller/webhooks.yaml
  cmd/controller/main.go
  internal/webhook/v1alpha1/scanjob_webhook.go
  internal/webhook/v1alpha1/scanjob_webhook_test.go
Labels: controller, feature, helm

#350 build(deps): bump cert-manager to 1.18.2
  Tiltfile
  test/e2e/main_test.go
Labels: chore
