Repository rancher-sandbox/sbombastic, pull requests merged in 2025-05, with the labels that each got.

#181 feat: add e2e test for sbombastic
  .dockerignore
  .github/workflows/e2e.yml
  Makefile
  Tiltfile
  go.mod
  go.sum
  helm/templates/storage/deployment.yaml
  helm/values.yaml
  test/e2e/e2e_suite_test.go
  test/e2e/main_test.go
Labels: ci

#208 fix: sbom generate with digest not the tag, add other platform into test cases with unify naming style.
  .github/workflows/ci.yml
  cmd/storage/main.go
  internal/handlers/generate_sbom.go
  internal/handlers/generate_sbom_test.go
  internal/handlers/scan_sbom_test.go
  test/e2e/e2e_suite_test.go
  test/fixtures/golang-1.12-alpine-386.sarif.json
  test/fixtures/golang-1.12-alpine-386.spdx.json
  test/fixtures/golang-1.12-alpine-amd64.sarif.json
  test/fixtures/golang-1.12-alpine-amd64.spdx.json
  test/fixtures/golang-1.12-alpine-arm-v6.sarif.json
  test/fixtures/golang-1.12-alpine-arm-v6.spdx.json
  test/fixtures/golang-1.12-alpine-arm-v7.sarif.json
  test/fixtures/golang-1.12-alpine-arm-v7.spdx.json
  test/fixtures/golang-1.12-alpine-arm64-v8.sarif.json
  test/fixtures/golang-1.12-alpine-arm64-v8.spdx.json
  test/fixtures/golang-1.12-alpine-ppc64le.sarif.json
  test/fixtures/golang-1.12-alpine-ppc64le.spdx.json
  test/fixtures/golang-1.12-alpine-s390x.sarif.json
  test/fixtures/golang-1.12-alpine-s390x.spdx.json
Labels: bug

#220 fix(.dockerignore): include bin directory for Tilt development builds
  .dockerignore
Labels: bug, dx, docker

#221 chore: tune golangci-lint configuration
  .golangci.yml
Labels: chore, ci

#222 fix(Tiltfile): change worker restart_file location
  Tiltfile
Labels: bug, dx

#225 test(e2e): export cluster logs
  .github/workflows/e2e.yml
  .gitignore
  test/e2e/main_test.go
Labels: ci
