Repository rancher-sandbox/sbombastic, pull requests merged in 2025-06, with the labels that each got.

#229 ci(e2e): workaround, fix no space left on device GH action runner error
  .github/workflows/e2e.yml
Labels: bug, ci

#240 ci: add rancher annotation
  helm/Chart.yaml
  helm/app-readme.md
Labels: ci

#244 nats: enable NATS mTLS
  .mockery.yml
  Makefile
  Tiltfile
  cmd/controller/main.go
  cmd/worker/main.go
  go.mod
  helm/templates/controller/cert-manager.yaml
  helm/templates/controller/deployment.yaml
  helm/templates/nats/cert-manager.yaml
  helm/templates/storage/pvc.yaml
  helm/templates/worker/cert-manager.yaml
  helm/templates/worker/deployment.yaml
  helm/values.yaml
  internal/controller/image_controller.go
  internal/controller/image_controller_test.go
  internal/controller/registry_controller.go
  internal/controller/registry_controller_test.go
  internal/controller/sbom_controller.go
  internal/controller/sbom_controller_test.go
  internal/messaging/mocks/publisher.go
  internal/messaging/nats.go
  internal/messaging/publisher.go
  internal/messaging/publisher_test.go
  internal/messaging/subscriber.go
  internal/messaging/subscriber_test.go
  internal/messaging/utils_test.go
  test/e2e/main_test.go
Labels: controller, worker, feature, helm

#263 fix: add permission when calling attestion generation
  .github/workflows/container-build.yaml
Labels: ci

#271 ci: run commitlint as part of our PRs
  .github/workflows/ci.yml
  commitlint.config.js
Labels: ci

#275 feat(controller): add ScanJob reconciler
  .golangci.yml
  api/v1alpha1/scanjob_types.go
  cmd/controller/main.go
  helm/templates/controller/role.yaml
  helm/templates/crd/sbombastic.rancher.io_scanjobs.yaml
  internal/controller/image_controller_test.go
  internal/controller/registry_controller_test.go
  internal/controller/sbom_controller_test.go
  internal/controller/scanjob_controller.go
  internal/controller/scanjob_controller_test.go
  internal/controller/suite_test.go
Labels: controller, feature
